name: "ğŸš€ Publish NPM Package"

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type to be published [major | minor | patch]'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

env:
  node_version: 18
  
concurrency: # prevent concurrent releases
  group: publish-npm-package
  cancel-in-progress: true

jobs:
  publish-npm:
    name: 'ğŸš€ publish'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'ğŸ“š checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 'ğŸŸ¢ setup node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org/

      - name: 'âš™ï¸ installing dependencies'
        run: npm ci

      - name: 'Configure Git access'
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions[bot]@github.com

      - name: 'Bump the package version'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_ACCESS_TOKEN }}
        run: npm version ${{ github.event.inputs.release-type }}

      - name: 'Commit new version to git'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_ACCESS_TOKEN }}
        run: |
          git show
          git push --follow-tags
          
      - name: 'ğŸš€ publish to npmjs.org registry'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

      - name: 'Create Release in repository'
        run: |
          RELEASE_TAG=$(git describe --tags $(git rev-list --tags --max-count=1)
          gh release create $RELEASE_TAG --latest --verify-tag
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_ACCESS_TOKEN }}
