name: "ğŸš€ Publish NPM Package"

on:
# Uncomment to work with releases
#  release:
#    types: [published]
  push:
    branches:
      - 'master'

jobs:
  publish-npm:
    name: 'ğŸš€ publish'
    runs-on: ubuntu-latest
    steps:
      - name: 'ğŸ“š checkout repository'
        uses: actions/checkout@v4

      - name: 'ğŸŸ¢ setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: 'âš™ï¸ installing dependencies'
        run: npm ci
          
      - name: 'ğŸš€ publish to npmjs.org registry'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
